server:
  port: 9090


dubbo:
  application:
    name: dubbo_client
  registry:
    protocol: zookeeper
    address: 106.13.181.6:2181
  scan:
    base-packages: com.example.demo.controller
debug: true